Repository awsdocs/aws-doc-sdk-examples-tools, pull requests merged in 2024-08, with the labels that each got.

#72 GitHub label check
  .github/allowed-labels.yaml
  .github/workflows/label_check.yml
Labels: Enhancement

#68 Remove snippet tags from snippet files
  aws_doc_sdk_examples_tools/doc_gen.py
  aws_doc_sdk_examples_tools/doc_gen_test.py
  aws_doc_sdk_examples_tools/metadata_test.py
  aws_doc_sdk_examples_tools/snippets.py
  aws_doc_sdk_examples_tools/snippets_test.py
  aws_doc_sdk_examples_tools/test_resources/snippet_file.txt
  aws_doc_sdk_examples_tools/test_resources/valid_metadata.yaml
Labels: Enhancement

#74 Normalize workflow yaml extensions.
  .github/workflows/label_check.yaml
  .github/workflows/label_reconciler.yaml
  .github/workflows/pr_stats.yaml
  .github/workflows/test.yaml
Labels: Enhancement

#77 Release/2024 08 26 a
  README.md
  setup.py
Labels: Bug

#69 Validate that github path items are reachable from the root
  aws_doc_sdk_examples_tools/doc_gen.py
  aws_doc_sdk_examples_tools/metadata.py
  aws_doc_sdk_examples_tools/metadata_errors.py
  aws_doc_sdk_examples_tools/metadata_test.py
  aws_doc_sdk_examples_tools/test_resources/errors_metadata.yaml
  aws_doc_sdk_examples_tools/test_resources/formaterror_metadata.yaml
  aws_doc_sdk_examples_tools/test_resources/test_path/snippet_file.txt
  aws_doc_sdk_examples_tools/test_resources/valid_metadata.yaml
Labels: Enhancement

#78 Update sdks.yaml to match root repo.
  aws_doc_sdk_examples_tools/config/sdks.yaml
Labels: Bug, Task

#80 Skip github path check for full path links.
  aws_doc_sdk_examples_tools/metadata.py
Labels: Bug
