Repository awsdocs/aws-doc-sdk-examples-tools, pull requests merged in 2024-09, with the labels that each got.

#81 Perform github path check during validation, rather than metadata parsing.
  aws_doc_sdk_examples_tools/doc_gen.py
  aws_doc_sdk_examples_tools/metadata.py
  aws_doc_sdk_examples_tools/metadata_test.py
Labels: Enhancement, Task

#82 Update README.md
  README.md
Labels: Enhancement, Task

#83 Release 2024-09-04-A
  setup.py
Labels: Enhancement, Task

#84 Update name for Amazon Bedrock Agents
  aws_doc_sdk_examples_tools/config/services.yaml
Labels: Enhancement, Task

#85 Release 2023-09-11-A
  setup.py
Labels: Enhancement, Task

#86 Remove bookmark override link from Java SDK metadata
  aws_doc_sdk_examples_tools/config/sdks.yaml
Labels: Bug

#87 Update setup.py to latest tagged version.
  setup.py
Labels: Enhancement

#90 Meta: Add new services to support CLI examples.
  aws_doc_sdk_examples_tools/config/services.yaml
Labels: Enhancement

#91 Update release tag in setup.py.
  setup.py
Labels: Enhancement

#92 Meta: Remove Swift prerelease caveat.
  aws_doc_sdk_examples_tools/config/sdks.yaml
  setup.py
Labels: Enhancement

#93 Feat: Add terraform to list of files in snippet search.
  aws_doc_sdk_examples_tools/validator_config.py
Labels: Enhancement, Task

#94 Meta: Bundle marketplace services.
  aws_doc_sdk_examples_tools/config/services.yaml
Labels: Enhancement

#95 Meta: Change sort order of marketplace sub-services per service team request.
  aws_doc_sdk_examples_tools/config/services.yaml
Labels: Enhancement
