Repository awsdocs/aws-doc-sdk-examples-tools, pull requests merged in 2024-10, with the labels that each got.

#102 Meta: Bundle S3 and S3 Control examples.
  aws_doc_sdk_examples_tools/config/services.yaml
Labels: Enhancement

#103 DocGen: changes to correctly merge metadata from tributaries
  aws_doc_sdk_examples_tools/doc_gen.py
Labels: Enhancement

#100 Update instructions to use YYYY.WW.REV for release versions.
  README.md
  setup.py
  stamp.sh
Labels: Enhancement, Task

#104 Use branch --show-current for current branch name
  stamp.sh
Labels: Bug

#105 Extract ErrorsList base errors list manager
  aws_doc_sdk_examples_tools/entities.py
  aws_doc_sdk_examples_tools/entities_test.py
  aws_doc_sdk_examples_tools/metadata_errors.py
Labels: Enhancement, Task

#108 DocGen - Update doc_gen.py
  aws_doc_sdk_examples_tools/doc_gen.py
Labels: Enhancement

#109 Release 2024.42.0
  setup.py
Labels: Enhancement

#110 Meta: Add JavaScript runtime for CloudFront Functions to sdks.yaml.
  aws_doc_sdk_examples_tools/config/sdks.yaml
Labels: Enhancement

#112 Update README.md
  README.md
Labels: Enhancement, Task

#113 Move from_yaml methods out of metadata.py and into their own file.
  aws_doc_sdk_examples_tools/doc_gen.py
  aws_doc_sdk_examples_tools/metadata.py
  aws_doc_sdk_examples_tools/metadata_test.py
  aws_doc_sdk_examples_tools/yaml_mapper.py
Labels: Enhancement

#114 Meta: Fix s3control service version and other fields in services.yaml.
  aws_doc_sdk_examples_tools/config/services.yaml
Labels: Bug
