Repository awsdocs/aws-doc-sdk-examples-tools, pull requests merged in 2024-11, with the labels that each got.

#117 Yaml:Add transcribe streaming to services.yaml
  aws_doc_sdk_examples_tools/config/services.yaml
Labels: Enhancement

#119 Add eventbridge pipes service
  aws_doc_sdk_examples_tools/config/services.yaml
Labels: Enhancement, Task

#118 Meta: S3 directory bucket subservice
  aws_doc_sdk_examples_tools/config/sdks.yaml
  aws_doc_sdk_examples_tools/config/services.yaml
Labels: Enhancement

#120 Remove bundles from services that do have distinct guides.
  action.yaml
  aws_doc_sdk_examples_tools/config/services.yaml
Labels: Bug, Task

#121 Meta: Bundle S3 directory buckets and fix a typo in pipes version.
  aws_doc_sdk_examples_tools/config/services.yaml
Labels: Enhancement
