Repository awsdocs/aws-doc-sdk-examples-tools, pull requests merged in 2024-12, with the labels that each got.

#124 Validator: Re-enable yamale validator.
  aws_doc_sdk_examples_tools/config/example_schema.yaml
  aws_doc_sdk_examples_tools/config/example_strict_schema.yaml
  aws_doc_sdk_examples_tools/config/sdks_schema.yaml
  aws_doc_sdk_examples_tools/config/services_schema.yaml
  aws_doc_sdk_examples_tools/doc_gen.py
  aws_doc_sdk_examples_tools/metadata_validator.py
  aws_doc_sdk_examples_tools/metadata_validator_test.py
  aws_doc_sdk_examples_tools/test_resources/doc_gen_test/.doc_gen/metadata/aws_entity_metadata.yaml
Labels: Bug

#125 Update link_template for Swift in sdks.yaml
  aws_doc_sdk_examples_tools/config/sdks.yaml
Labels: Bug

#126 DocGen: add complex categories
  aws_doc_sdk_examples_tools/categories.py
  aws_doc_sdk_examples_tools/categories_test.py
  aws_doc_sdk_examples_tools/config/categories.yaml
  aws_doc_sdk_examples_tools/doc_gen.py
  aws_doc_sdk_examples_tools/metadata_errors.py
  aws_doc_sdk_examples_tools/metadata_test.py
  aws_doc_sdk_examples_tools/test_resources/categories.yaml
  aws_doc_sdk_examples_tools/test_resources/empty_categories.yaml
  aws_doc_sdk_examples_tools/test_resources/formaterror_metadata.yaml
  aws_doc_sdk_examples_tools/yaml_mapper.py
Labels: Enhancement

#127 Add S3 only entity and fix error to derive from Exception.
  aws_doc_sdk_examples_tools/config/entities.yaml
  aws_doc_sdk_examples_tools/entities.py
Labels: Bug

#128 validator: Remove example ID check from yamale validator
  aws_doc_sdk_examples_tools/metadata_validator.py
Labels: Bug

#129 Remove unused 1click service entries
  aws_doc_sdk_examples_tools/config/services.yaml
Labels: Enhancement, Task
