Repository awsdocs/aws-doc-sdk-examples-tools, pull requests merged in 2025-01, with the labels that each got.

#130 Generically handle all entities in DocGen entity expansion.
  aws_doc_sdk_examples_tools/doc_gen.py
  aws_doc_sdk_examples_tools/doc_gen_cli.py
  aws_doc_sdk_examples_tools/doc_gen_test.py
  aws_doc_sdk_examples_tools/entities.py
  aws_doc_sdk_examples_tools/entities_test.py
Labels: Enhancement

#131 doc_gen_cli collects and stores snippets in a second file
  aws_doc_sdk_examples_tools/doc_gen_cli.py
  aws_doc_sdk_examples_tools/doc_gen_cli_test.py
Labels: Enhancement

#133 Add CloudWatch Observability Admin service to metadata.
  aws_doc_sdk_examples_tools/config/services.yaml
Labels: Enhancement

#134 Ensure entities are copied during clone.
  aws_doc_sdk_examples_tools/doc_gen.py
Labels: Bug

#135 Add CloudWatch Synthetics service metadata
  aws_doc_sdk_examples_tools/config/services.yaml
Labels: Enhancement, Task

#137 Add Directory Service Data service metadata.
  aws_doc_sdk_examples_tools/config/services.yaml
Labels: Enhancement, Task

#136 Add CloudWatch Observability Access Monitor service config.
  aws_doc_sdk_examples_tools/config/services.yaml
Labels: Enhancement, Task
