Repository awsdocs/aws-doc-sdk-examples-tools, pull requests merged in 2025-04, with the labels that each got.

#152 Added author and owner fields at the example version level.
  aws_doc_sdk_examples_tools/metadata.py
  aws_doc_sdk_examples_tools/metadata_errors.py
  aws_doc_sdk_examples_tools/metadata_test.py
  aws_doc_sdk_examples_tools/test_resources/errors_metadata.yaml
  aws_doc_sdk_examples_tools/yaml_mapper.py
Labels: Enhancement

#153 Load and merge config before examples
  aws_doc_sdk_examples_tools/doc_gen.py
Labels: Bug

#154 Track source URL from sdk_version.
  aws_doc_sdk_examples_tools/metadata.py
  aws_doc_sdk_examples_tools/yaml_mapper.py
Labels: Enhancement, Task

#156 Adding .NET v4 to SDK definitions
  aws_doc_sdk_examples_tools/config/sdks.yaml
Labels: Enhancement

#157 Remove yamale check to validate example service
  aws_doc_sdk_examples_tools/config/example_schema.yaml
  aws_doc_sdk_examples_tools/config/example_strict_schema.yaml
Labels: Enhancement

#158 Added IoT fleetwise to service YAML
  aws_doc_sdk_examples_tools/config/services.yaml
Labels: Enhancement

#159 Add script for generating new titles/descriptions for snippet metadata.
  aws_doc_sdk_examples_tools/scripts/make_prompts.py
  aws_doc_sdk_examples_tools/scripts/policy.json.example.md
Labels: Enhancement

#161 Add yaml writer to update doc_gen metadata.
  aws_doc_sdk_examples_tools/yaml_writer.py
  aws_doc_sdk_examples_tools/yaml_writer_test.py
Labels: Enhancement, Task
